### Note: SS read names should not have "_" character

sample: HG00733
Nchunks: 100

graphfolder: ../../DBG_illumina/
# required for building the de Bruijn graph
bcalmpath: /MMCI/TM/scratch/mikko/random_bins/bcalm_2_2
bcalm_converttoGFApath: /MMCI/TM/scratch/mikko/random_bins/convertToGFA.py

# whatshap
whatshap: ../../whatshap-env/bin/whatshap
BubbleGun: /home/mgharegh/.local/bin/BubbleGun

overlap_graph: "FLASE"

# whatshap split command
whatshap_split_add_untagged: True


# PacBio reads
pb_bam_dir: ../../ccs_bams
min_pb_len: 5000


reference: ../../hg38.fa
phased_references: ["phased_references/HG00733.chr8.h0.polish.fasta", "phased_references/HG00733.chr8.h1.polish.fasta"]

phased_vcf_dir: trio-based-phasing/
vcf_prefix: SH032

# SS bams and phased vcf files
SS_bam_dir: ../../ss_bams

# Kmer size of the graph
# This should be very low to prevent fragmentation
k: 63
l: 23

# Minimum kmer abundance of the graph
# This should be very low
kmer_abundance: 3


# directory including all Strand-seq fastq files
SS_fastq_dir: ../../ss_fastq


het_kmer_len: 10

#minimap parameters
w: 1
k_minimap: 15
f: 0.1 #0.0002
z: 500

# saarclust parameters
testNumClustersHard: 70
numClustersHard: 70
numClustersSoft: 47
EMiter: 10
alpha: 0.01
minLib: 1
upperQ: 0.95
logLth: 1
theta_constrain: "FALSE"
log_scale: "TRUE"
numAlignments: 150000
haploclust_itr: 10

hifiasm: hifiasm/hifiasm
